---
- name: This playbook is dedicated to taking backup related to infra servers
  hosts: infra
  gather_facts: False
  tasks:
        - name: Executing tasks via external yml
          include_tasks: backup.yml
          with_items:
            - "{{ folders }}" #Obtained from the host_vars
